[2025-07-30T11:17:41.788+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-07-30T11:17:41.993+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Premier_dag.scraping_group.scrap_emploi_dakar manual__2025-07-30T11:17:30.207650+00:00 [queued]>
[2025-07-30T11:17:42.015+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Premier_dag.scraping_group.scrap_emploi_dakar manual__2025-07-30T11:17:30.207650+00:00 [queued]>
[2025-07-30T11:17:42.016+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 1
[2025-07-30T11:17:42.045+0000] {taskinstance.py:2327} INFO - Executing <Task(BashOperator): scraping_group.scrap_emploi_dakar> on 2025-07-30 11:17:30.207650+00:00
[2025-07-30T11:17:42.057+0000] {standard_task_runner.py:63} INFO - Started process 58 to run task
[2025-07-30T11:17:42.061+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'Premier_dag', 'scraping_group.scrap_emploi_dakar', 'manual__2025-07-30T11:17:30.207650+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/PremierDagLake.py', '--cfg-path', '/tmp/tmpae1snz73']
[2025-07-30T11:17:42.063+0000] {standard_task_runner.py:91} INFO - Job 3: Subtask scraping_group.scrap_emploi_dakar
[2025-07-30T11:17:42.102+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-07-30T11:17:42.165+0000] {task_command.py:426} INFO - Running <TaskInstance: Premier_dag.scraping_group.scrap_emploi_dakar manual__2025-07-30T11:17:30.207650+00:00 [running]> on host 03609ac50de5
[2025-07-30T11:17:42.307+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='Premier_dag' AIRFLOW_CTX_TASK_ID='scraping_group.scrap_emploi_dakar' AIRFLOW_CTX_EXECUTION_DATE='2025-07-30T11:17:30.207650+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-07-30T11:17:30.207650+00:00'
[2025-07-30T11:17:42.309+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-07-30T11:17:42.310+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-07-30T11:17:42.311+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'cd /opt/***/scrapjob/spiders && scrapy crawl emploi_dakar']
[2025-07-30T11:17:42.331+0000] {subprocess.py:86} INFO - Output:
[2025-07-30T11:17:42.334+0000] {subprocess.py:93} INFO - /usr/bin/bash: line 1: cd: /opt/***/scrapjob/spiders: No such file or directory
[2025-07-30T11:17:42.334+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-07-30T11:17:42.335+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-07-30T11:17:42.352+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-07-30T11:17:42.359+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=Premier_dag, task_id=scraping_group.scrap_emploi_dakar, execution_date=20250730T111730, start_date=20250730T111741, end_date=20250730T111742
[2025-07-30T11:17:42.378+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 3 for task scraping_group.scrap_emploi_dakar (Bash command failed. The command returned a non-zero exit code 1.; 58)
[2025-07-30T11:17:42.396+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-07-30T11:17:42.473+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-07-30T11:17:42.484+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
